#!/usr/bin/env php
<?php
/**
 * Created by PhpStorm.
 * User: 明月有色
 * Date: 2018/10/26
 * Time: 14:53
 */

use Easy\Scheduler;
use Easy\Socket\HttpConnect;

require_once 'vendor/autoload.php';

$scheduler = new Scheduler();
$scheduler->monitor(new HttpConnect(),'0.0.0.0:8080');
$scheduler->run();