#!/usr/bin/env php
<?php
/**
 * Created by PhpStorm.
 * User: 明月有色
 * Date: 2018/10/26
 * Time: 14:53
 */

use Doctrine\Common\Annotations\AnnotationRegistry;
use Utopia\Application;

$loader = require './vendor/autoload.php';

AnnotationRegistry::registerLoader(array($loader, "loadClass"));
Application::setLoader($loader);

$application = new Application(__DIR__);

/**
 * 基础配置加载
 * 核心服务引导加载
 */
$application->loadBaseConfig();
$application->loadServiceProvider();

$application->run();